### ISSUE TITLE
Out of date standard, or non-compliance?

### ISSUE THREAD

**Issue by rhoegg** [ok-omes/OMES.RepoStandards#3]
Hi, I'm about to migrate some code into OMES and I want to do it "the right way", but there are some repositories similar to mine being actively developed that follow a very different naming standard:

- https://github.com/ok-omes/omes-net-aws-tf-345-shakecast-t
- https://github.com/ok-omes/omes-net-gcp-tf-090-fin-d
- https://github.com/ok-omes/omes.gcp.networking
- https://github.com/ok-omes/ok-infra-baseline

If the standard needs to be updated, maybe this issue should be labeled "Improvement".  If the repos need to be renamed, what's the right way to get things moving?

I am planning to follow this repository's standards for my new repositories at present. Here is an example of mine:
- https://github.com/ok-omes/OMES.VerifyOK.Networking

**Comment by ghost** [comment]
Closing for no comments, and not having much/any standards established for this practice :)
